project:
  title: "Neural Networks for Physical Modelling Synthesis"
  output-dir: docs
  render:
    - slides.qmd

format:
  revealjs:
    theme: solarized
    incremental: false
    slide-number: true
    show-notes: false



